pathtiTrain = "C:\Users\lucaf\Desktop\EAI\Ophtamologia\Tesi\data";

%% Rete sperimentale
inLayer = imageInputLayer([256 256 3]);
midLayers = [ convolution2dLayer(11, 3); reluLayer(); maxPooling2dLayer(2);...
    convolution2dLayer(5, 96); reluLayer(); maxPooling2dLayer(2); convolution2dLayer(3, 192);...
    maxPooling2dLayer(2); convolution2dLayer(3, 192);maxPooling2dLayer(2)];
outLayers = [fullyConnectedLayer(2); softmaxLayer();fullyConnectedLayer(2); softmaxLayer();classificationLayer()];

ChenLayer = [inLayer; midLayers; outLayers];
inputSize = ChenLayer(1).InputSize

%% Datastore e Augmentation
imds = imageDatastore(pathtiTrain,'IncludeSubfolders',true,'LabelSource','foldernames');
[trainImgs,testImgs] = splitEachLabel(imds,0.8,0.2,'randomized');

pixelRange = [-10 10];
scaleRange = [0.9 1.1];
angleRange = [-30 30];
imageAugmenter = imageDataAugmenter( ...
    'RandYReflection',true, ...
    'RandXTranslation',pixelRange, ...
    'RandYTranslation',pixelRange, ...
    'RandXScale',scaleRange, ...
    'RandYScale',scaleRange, ...
    'RandRotation', angleRange);

trainAug= augmentedImageDatastore(inputSize(1:2),trainImgs);
testAug = augmentedImageDatastore(inputSize(1:2),testImgs); %validation

miniBatchSize = 5;
valFrequency = floor(numel(trainAug.Files)/miniBatchSize);
options = trainingOptions('sgdm', ...
    'MiniBatchSize',miniBatchSize, ...
    'MaxEpochs',8, ...
    'InitialLearnRate',0.001, ...
    'Shuffle','every-epoch', ...
    'ValidationData',testAug, ...
    'ValidationFrequency',valFrequency, ...
    'Verbose',false, ...
    'Plots','training-progress');
landnet = trainNetwork(trainAug, ChenLayer, options);

[YPred,probs] = classify(landnet, testAug);
accuracy = mean(YPred == testImgs.Labels)

confusionchart(testImgs.Labels,YPred)
